name: docs
on:
  push:
    tags:
      - '*.*.*'
    branches:
      - main
  workflow_dispatch:
env:
  nim-version: 'stable'
  module-name: 'libevent'
  nim-src: src/${{ env.module-name }}.nim
  deploy-dir: .gh-pages
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ env.nim-version }}
      - run: nimble install -Y
      - run: nim doc --index:on --project --path:. --out:${{ env.deploy-dir }} ${{ env.nim-src }}
      
      - name: "Rename to index.html"
        run: mv ${{ env.deploy-dir }}/${{ env.module-name }}.html ${{ env.deploy-dir }}/index.html 
      
      - name: "Find and replace (index.html)"
        run: sed -i 's/${{ env.module-name }}.html/index.html/g' ${{ env.deploy-dir }}/index.html

      - name: "Find and replace (theindex.html)"
        run: sed -i 's/${{ env.module-name }}.html/index.html/g' ${{ env.deploy-dir }}/theindex.html
        
      - name: Deploy documents
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.deploy-dir }}
